281 vite config
NoroffFEU/agency.noroff.dev pull request #596
Opened 2024-01-10 10:19 UTC by Spookyrumble

Adds index.scss import to index.js.
Adds config to vite.config.js.
Updates readme to reflect changes.
Updates readme to update vite.config.js if new HTML files are added to the project.

2024-01-10 18:20 UTC, kyrregjerstad requested changes
Awesome work @Spookyrumble, looks great!🔥 

I only got some minor requests and suggestions. Nice touch with the updated readme!

One other file that needs to be updated is the `.github/workflows/static.yml` file which tells github pages what to deploy. This should now be:

```yml
          # Upload entire repository
          path: './dist'
```

on line 45.

Let me know if you got any questions and keep up the good work 🚀

2024-01-10 18:20 UTC, kyrregjerstad commented on vite.config.js
> +/* eslint-disable no-undef */
Let's try not to disable eslint guard rails ;) 

A solution could be to do something like this instead:

```suggestion
import * as path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
```

this way you don't have to turn of undefined checking for the whole file.

2024-01-10 18:20 UTC, kyrregjerstad commented on vite.config.js
> +    outDir: path.resolve(__dirname, '/dist'),
this needs to be 

```suggestion
    outDir: path.resolve(__dirname, './dist'),

```

so that it stays relative to the root dir

2024-01-10 18:20 UTC, kyrregjerstad commented on vite.config.js
> +  // base: '/',
let's remove dead comments

2024-01-10 18:20 UTC, kyrregjerstad commented on vite.config.js
> +  build: {
I would suggest adding `emptyOutDir: true,` here as well

2024-01-10 18:20 UTC, kyrregjerstad commented on index.html
>      <link href="/css/index.css" rel="stylesheet" />
This line needs to be removed from all HTML files, since Vite is now taking care of it through index.js

2024-01-11 10:07 UTC, kyrregjerstad commented
LGTM

2024-01-11 11:09 UTC, Sovak3441 approved these changes
Great work! And it looks good too :)

2024-01-11 12:31 UTC, merged