#763 change img src path
NoroffFEU/agency.noroff.dev pull request #850
Opened 2024-01-16 21:54 UTC by mariajaro

Path to images and icons should not use the public in paths

../../public/images/logoipsum-287.svg" WRONG
/images/logoipsum-287.svg" CORRECT

../../public/assets/icons/filter.svg" WRONG
/assets/icons/filter.svg" CORRECT

Filter icon has Search icon as alt text:

<img
      src="../../public/assets/icons/filter.svg"
      alt="Search icon"
      class="icon-sm"
    />
Missing alt text:

<img src="../../public/images/logoipsum-287.svg" class="rounded-start" alt="..." />

2024-01-16 22:49 UTC, Olekrr requested changes
Hello Maria, I have reviewed your PR and there are a couple of things you need to look at. Please refer to my comments

2024-01-16 22:49 UTC, Olekrr commented on index.html
> +>>>>>>> Stashed changes
You seem to have some stashed changes leftover in your code that needs to be removed

2024-01-16 22:49 UTC, Olekrr commented on pages/listings/index.html
> +<<<<<<< Updated upstream
What is this?

2024-01-16 22:49 UTC, Olekrr commented on pages/listings/index.html
> +>>>>>>> Stashed changes
More stashed changes

2024-01-17 18:00 UTC, mariajaro commented on pages/listings/index.html
> +<<<<<<< Updated upstream
removed

2024-01-17 18:00 UTC, mariajaro commented on pages/listings/index.html
> +>>>>>>> Stashed changes
removed

2024-01-17 19:26 UTC, Olekrr requested changes
Hi Maria, mostly this is fixed but it looks like there is a bit left. Refer to my comments

2024-01-17 19:26 UTC, Olekrr commented on index.html
>  </html>
There are still some issues here that needs to be resolved. There seems to be additional section, main, footer, body and html closing tags

2024-01-17 19:26 UTC, Olekrr commented on index.html
> +<<<<<<< Updated upstream
What is this line?

2024-01-17 19:51 UTC, mariajaro commented on index.html
> +<<<<<<< Updated upstream
removed

2024-01-18 12:19 UTC, Olekrr commented
This has in the meantime been completed by a different group, as such this task is redundant and will be closed without a merge.

2024-01-18 12:19 UTC, closed without merging