changed font size on h2
NoroffFEU/agency.noroff.dev pull request #900
Opened 2024-01-17 19:08 UTC by haiderf7

## Title

## Describe your changes: 

## Type of changes:

## Checklist before requesting a review

* [ ] I created a new branch before starting with this ticket?
* [ ] I commented the issue after finish in the Frontend Team Board?
* [ ] I moved the card to Quality Assurance after finish?

## Did you run into any issues?

- No, issues encountered.
- Yes, I encountered issues. (Please describe below).

## Screenshots:

- No screenshots to include.
- Yes, the screenshots are included in the table below.

| Before | After |
---------|--------
|        |       |

## Additional information:

## Feedback

- No, I don't want feedback.
- Yes, I want feedback.

2024-01-17 19:17 UTC, runeunhjem reviewed
Think you have imported it into the wrong index.js :)
<script defer src="/index.js" type="module"></script>

This means root/index.js

2024-01-17 19:44 UTC, haiderf7 commented
i think i have it in the right index.js now?

2024-01-17 19:58 UTC, Olekrr requested changes

2024-01-17 19:58 UTC, Olekrr commented on index.js
> +import { adjustH2FontSize } from './listingTemplate.js';
Your file import here seems to be incorrect and is resulting in a linting error. Please take a look at this

2024-01-17 20:09 UTC, haiderf7 commented
fixed it now

2024-01-18 12:31 UTC, Olekrr commented
This issue has been solved elsewhere, as such this PR will be closed without merging.

2024-01-18 12:31 UTC, closed without merging